In [41]:
import pandas as pd
import numpy as np

In [42]:
df=pd.read_csv('Housing.csv')

In [43]:
num_cols=df.select_dtypes(include=['int64','float64']).columns
cat_cols=df.select_dtypes(include=['object']).columns

In [44]:
cat_cols

Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [45]:
cat_cols.shape,num_cols.shape,df.shape

((7,), (6,), (545, 13))

In [46]:
can_be_cat=[]
for i in num_cols:
    x=df[i].value_counts().shape[0] 
    
    if x<= 15:
       can_be_cat.append(i)

In [47]:
can_be_cat

['bedrooms', 'bathrooms', 'stories', 'parking']

In [48]:
numreic_col=[]

for i in num_cols:
    if i not in can_be_cat:
       numreic_col.append(i)

In [49]:
numreic_col

['price', 'area']

In [50]:
for i in can_be_cat:
    cat_cols=np.append(cat_cols,i)
cat_cols

array(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus', 'bedrooms',
       'bathrooms', 'stories', 'parking'], dtype=object)

In [51]:
prob=[]
for i in cat_cols:
    x=df[i].value_counts().values/(df[i].value_counts().values.sum())

    prob.append(x)
prob

[array([0.8587156, 0.1412844]),
 array([0.82201835, 0.17798165]),
 array([0.64954128, 0.35045872]),
 array([0.95412844, 0.04587156]),
 array([0.68440367, 0.31559633]),
 array([0.76513761, 0.23486239]),
 array([0.41651376, 0.3266055 , 0.25688073]),
 array([0.55045872, 0.24954128, 0.17431193, 0.01834862, 0.00366972,
        0.00366972]),
 array([0.73577982, 0.2440367 , 0.01834862, 0.00183486]),
 array([0.43669725, 0.41651376, 0.07522936, 0.07155963]),
 array([0.54862385, 0.23119266, 0.19816514, 0.02201835])]

In [52]:
curr_entropy=0

for i in prob:
    for j in i:
        curr_entropy+=(-j*np.log2(j))

curr_entropy

np.float64(11.381594352931907)

In [53]:
num_prob=[]
for i in numreic_col:
    binn=pd.cut(df[i],bins=15)
    num_prob.append(binn.value_counts().values/(binn.value_counts().values.sum()))
 

In [54]:

for i in num_prob:
    for j in i:
        if j!=0:
           curr_entropy+=(-j*np.log2(j))

In [55]:
curr_entropy

np.float64(17.486418283171574)

In [57]:
from scipy.stats import entropy

def calc_entropy(series):
    counts = series.value_counts()
    probs = counts / counts.sum()
    return entropy(probs, base=2)

# Example for all columns
entropy_values =0
for col in df.columns:
    entropy_values+=calc_entropy(df[col])

In [58]:
entropy_values

np.float64(26.298106647276068)