In [19]:
import pandas as pd
import numpy as np

In [20]:
df=pd.read_csv('faa_ai_prelim.csv')

In [21]:
df = df.fillna(df.mean(numeric_only=True))  # for numeric
df = df.fillna(df.mode().iloc[0])  

In [22]:
num_cols=df.select_dtypes(include=['int64','float64']).columns
cat_cols=df.select_dtypes(include=['object']).columns

In [23]:
cat_cols

Index(['UPDATED', 'ENTRY_DATE', 'EVENT_LCL_DATE', 'EVENT_LCL_TIME',
       'LOC_CITY_NAME', 'LOC_STATE_NAME', 'LOC_CNTRY_NAME', 'RMK_TEXT',
       'EVENT_TYPE_DESC', 'FSDO_DESC', 'REGIST_NBR', 'FLT_NBR', 'ACFT_OPRTR',
       'ACFT_MAKE_NAME', 'ACFT_MODEL_NAME', 'ACFT_DMG_DESC', 'FLT_ACTIVITY',
       'FLT_PHASE', 'MAX_INJ_LVL', 'FATAL_FLAG'],
      dtype='object')

In [24]:
cat_cols.shape,num_cols.shape,df.shape

((20,), (22,), (83, 42))

In [25]:

can_be_cat=[]
for i in num_cols:
    x=df[i].value_counts().shape[0] 
    
    if x<= 15:
       can_be_cat.append(i)

In [26]:

can_be_cat

['ACFT_MISSING_FLAG',
 'FAR_PART',
 'FLT_CRW_INJ_NONE',
 'FLT_CRW_INJ_MINOR',
 'FLT_CRW_INJ_SERIOUS',
 'FLT_CRW_INJ_FATAL',
 'FLT_CRW_INJ_UNK',
 'CBN_CRW_INJ_NONE',
 'CBN_CRW_INJ_MINOR',
 'CBN_CRW_INJ_SERIOUS',
 'CBN_CRW_INJ_FATAL',
 'CBN_CRW_INJ_UNK',
 'PAX_INJ_NONE',
 'PAX_INJ_MINOR',
 'PAX_INJ_SERIOUS',
 'PAX_INJ_FATAL',
 'PAX_INJ_UNK',
 'GRND_INJ_NONE',
 'GRND_INJ_MINOR',
 'GRND_INJ_SERIOUS',
 'GRND_INJ_FATAL',
 'GRND_INJ_UNK']

In [27]:
numreic_col=[]

for i in num_cols:
    if i not in can_be_cat:
       numreic_col.append(i)

In [28]:
numreic_col

[]

In [29]:
for i in can_be_cat:
    cat_cols=np.append(cat_cols,i)
cat_cols

array(['UPDATED', 'ENTRY_DATE', 'EVENT_LCL_DATE', 'EVENT_LCL_TIME',
       'LOC_CITY_NAME', 'LOC_STATE_NAME', 'LOC_CNTRY_NAME', 'RMK_TEXT',
       'EVENT_TYPE_DESC', 'FSDO_DESC', 'REGIST_NBR', 'FLT_NBR',
       'ACFT_OPRTR', 'ACFT_MAKE_NAME', 'ACFT_MODEL_NAME', 'ACFT_DMG_DESC',
       'FLT_ACTIVITY', 'FLT_PHASE', 'MAX_INJ_LVL', 'FATAL_FLAG',
       'ACFT_MISSING_FLAG', 'FAR_PART', 'FLT_CRW_INJ_NONE',
       'FLT_CRW_INJ_MINOR', 'FLT_CRW_INJ_SERIOUS', 'FLT_CRW_INJ_FATAL',
       'FLT_CRW_INJ_UNK', 'CBN_CRW_INJ_NONE', 'CBN_CRW_INJ_MINOR',
       'CBN_CRW_INJ_SERIOUS', 'CBN_CRW_INJ_FATAL', 'CBN_CRW_INJ_UNK',
       'PAX_INJ_NONE', 'PAX_INJ_MINOR', 'PAX_INJ_SERIOUS',
       'PAX_INJ_FATAL', 'PAX_INJ_UNK', 'GRND_INJ_NONE', 'GRND_INJ_MINOR',
       'GRND_INJ_SERIOUS', 'GRND_INJ_FATAL', 'GRND_INJ_UNK'], dtype=object)

In [30]:
prob=[]
for i in cat_cols:
    x=df[i].value_counts().values/(df[i].value_counts().values.sum())

    prob.append(x)
prob

[array([0.96385542, 0.03614458]),
 array([0.3253012 , 0.19277108, 0.15662651, 0.07228916, 0.06024096,
        0.06024096, 0.06024096, 0.03614458, 0.02409639, 0.01204819]),
 array([0.14457831, 0.09638554, 0.09638554, 0.08433735, 0.08433735,
        0.08433735, 0.06024096, 0.06024096, 0.06024096, 0.04819277,
        0.04819277, 0.03614458, 0.02409639, 0.02409639, 0.01204819,
        0.01204819, 0.01204819, 0.01204819]),
 array([0.03614458, 0.02409639, 0.02409639, 0.02409639, 0.02409639,
        0.02409639, 0.01204819, 0.01204819, 0.01204819, 0.01204819,
        0.01204819, 0.01204819, 0.01204819, 0.01204819, 0.01204819,
        0.01204819, 0.01204819, 0.01204819, 0.01204819, 0.01204819,
        0.01204819, 0.01204819, 0.01204819, 0.01204819, 0.01204819,
        0.01204819, 0.01204819, 0.01204819, 0.01204819, 0.01204819,
        0.01204819, 0.01204819, 0.01204819, 0.01204819, 0.01204819,
        0.01204819, 0.01204819, 0.01204819, 0.01204819, 0.01204819,
        0.01204819, 0.01204819, 0.

In [31]:
curr_entropy=0

for i in prob:
    for j in i:
        curr_entropy+=(-j*np.log2(j))

curr_entropy

np.float64(60.95847119965141)

In [32]:
num_prob=[]
for i in numreic_col:
    binn=pd.cut(df[i],bins=15)
    num_prob.append(binn.value_counts().values/(binn.value_counts().values.sum()))
 

In [33]:

for i in num_prob:
    for j in i:
        if j!=0:
           curr_entropy+=(-j*np.log2(j))

In [34]:
curr_entropy

np.float64(60.95847119965141)

In [35]:
from scipy.stats import entropy

def calc_entropy(series):
    counts = series.value_counts()
    probs = counts / counts.sum()
    return entropy(probs, base=2)

# Example for all columns
entropy_values =0
for col in df.columns:
    entropy_values+=calc_entropy(df[col])

In [36]:
entropy_values

np.float64(60.95847119965169)